### ISSUE TITLE
Limit jsonrpc batch request size

### ISSUE THREAD

**Issue by john-g-g** [steemit/jussi#140]
To assure smooth scaling and predictable behavior, we should decide on an implement a limit to the jsonrpc batch request size.

**Comment by john-g-g** [comment]
@roadscape you mentioned 500 was your default size, but I think that is too large. How would a lower size (100-300) impact hivemind?

**Comment by roadscape** [comment]
@john-g-g I'm not sure what the impact would be, but 250 sounds reasonable.

Do we need to think about finer-grained limits? E.g.:
 - get_blocks has entirely different perf profile due to caching?
   - but jussi could implement get_blocks_batch call to leverage it
      - but is this call itself batchable; what are its limits?
 - `get_accounts` is a single call but takes up to 1,000 items natively
 - heavy requests like `get_state` (fetching entire trees) should possibly never be batched

**Comment by inertia186** [comment]
I was testing `blocks_api.get_blocks` and found I could reliably request up to 2,600 blocks.  After that, I would get code `413 Request Entity Too Large`.
